name: every_door_plugin
description: "Every Door plugin framework"
version: 1.2.0
homepage: https://github.com/zverik/every_door_plugin

environment:
  sdk: ^3.9.0
  flutter: "^3.35.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  dart_eval: ^0.8.2
  flutter_eval: ^0.8.1
  flutter_map_eval:
    git:
      url: https://github.com/Zverik/flutter_map_eval.git
      ref: main
  path: ^1.9.1
  logging: ^1.0.2
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  dart_eval:
    git:
      url: https://github.com/Zverik/dart_eval.git
      ref: operators
  flutter_eval:
    git:
      url: https://github.com/Zverik/flutter_eval.git
      ref: no_icons

executables:
  edp: every_door_plugin
