name: every_door_plugin
description: "Every Door plugin framework"
version: 0.1.0
homepage: https://github.com/zverik/every_door_plugin

environment:
  sdk: ^3.9.0
  flutter: ">=3.35.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  country_coder: ^1.2.0
  dart_eval: ^0.8.3
  flutter_eval: ^0.8.1
  flutter_map: ^8.2.0
  flutter_map_eval: ^0.1.0
  latlong2: ^0.9.0
  path: ^1.9.1
  logging: ^1.0.2
  yaml: ^3.1.3
  yaml_writer: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

dependency_overrides:
  flutter_eval:
    git:
      url: https://github.com/Zverik/flutter_eval.git
      ref: no_icons

executables:
  edp: every_door_plugin
